// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models
{
    public partial class Unit
    {
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string ArchDescription { get; set; }
        public bool Make { get; set; }
        public decimal? FOW { get; set; }
        public decimal? FOH { get; set; }
        public decimal? FOD { get; set; }
        public decimal? ROW { get; set; }
        public decimal? ROH { get; set; }
        public string MakeFile { get; set; }
        public int? Level { get; set; }
        public string Room { get; set; }
        public int? ProjectID { get; set; }
        public int? ProductionID { get; set; }
        public string ProjectGroupID { get; set; }
    }
}