// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models
{
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            Inventory = new HashSet<Inventory>();
            OrderReceiptItems = new HashSet<OrderReceiptItems>();
            Part = new HashSet<Part>();
            PurchaseLineItem = new HashSet<PurchaseLineItem>();
        }

        public int UnitOfMeasureID { get; set; }
        public string UnitName { get; set; }

        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<OrderReceiptItems> OrderReceiptItems { get; set; }
        public virtual ICollection<Part> Part { get; set; }
        public virtual ICollection<PurchaseLineItem> PurchaseLineItem { get; set; }
    }
}